"""actualizar_modelo_partida

Revision ID: 0b1747c00de3
Revises: 47d53389a547
Create Date: 2026-04-06 03:48:29.962627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1747c00de3'
down_revision: Union[str, Sequence[str], None] = '47d53389a547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidas', sa.Column('codigo_sala', sa.String(), nullable=True))
    op.alter_column('partidas', 'jugador_2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_partidas_codigo_sala'), 'partidas', ['codigo_sala'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partidas_codigo_sala'), table_name='partidas')
    op.alter_column('partidas', 'jugador_2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('partidas', 'codigo_sala')
    # ### end Alembic commands ###
