"""Agregar snapshot json a partida

Revision ID: 47d53389a547
Revises: 914cbe52ab80
Create Date: 2026-01-31 21:49:01.286105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47d53389a547'
down_revision: Union[str, Sequence[str], None] = '914cbe52ab80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partidas', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('partidas', sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partidas', 'snapshot')
    op.drop_column('partidas', 'estado')
    # ### end Alembic commands ###
