"""add codigo_sala and nullable jugador_2

Revision ID: 8afa0e60d0d5
Revises: 0b1747c00de3
Create Date: 2026-04-06 03:56:41.100596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afa0e60d0d5'
down_revision: Union[str, Sequence[str], None] = '0b1747c00de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partidas', 'codigo_sala',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partidas', 'codigo_sala',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
