"""Creacion tablas

Revision ID: f938ccc01eed
Revises: 
Create Date: 2025-12-07 17:21:04.953841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f938ccc01eed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('ataque', sa.Integer(), nullable=True),
    sa.Column('defensa', sa.Integer(), nullable=True),
    sa.Column('coste', sa.Integer(), nullable=False),
    sa.Column('rareza', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartas_id'), 'cartas', ['id'], unique=False)
    op.create_index(op.f('ix_cartas_nombre'), 'cartas', ['nombre'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_pw', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('mazos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mazos_id'), 'mazos', ['id'], unique=False)
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('jugador_1_id', sa.Integer(), nullable=False),
    sa.Column('jugador_2_id', sa.Integer(), nullable=False),
    sa.Column('ganador_id', sa.Integer(), nullable=True),
    sa.Column('resultado_detalle', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ganador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jugador_1_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['jugador_2_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_id'), 'partidas', ['id'], unique=False)
    op.create_table('mazos_cartas',
    sa.Column('mazo_id', sa.Integer(), nullable=False),
    sa.Column('carta_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carta_id'], ['cartas.id'], ),
    sa.ForeignKeyConstraint(['mazo_id'], ['mazos.id'], ),
    sa.PrimaryKeyConstraint('mazo_id', 'carta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mazos_cartas')
    op.drop_index(op.f('ix_partidas_id'), table_name='partidas')
    op.drop_table('partidas')
    op.drop_index(op.f('ix_mazos_id'), table_name='mazos')
    op.drop_table('mazos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_cartas_nombre'), table_name='cartas')
    op.drop_index(op.f('ix_cartas_id'), table_name='cartas')
    op.drop_table('cartas')
    # ### end Alembic commands ###
